stages:
  - build
  - api test

api local build:
  stage: build
  image:
    name: kennethreitz/httpbin
    entrypoint: [""]
  script:
    - pwd
    - mkdir build
    - cd build
    - cat /etc/os-release > info.txt
    - lsb_relase -a >> info.txt
    - hostnamectl >> info.txt
    - uname -r >> info.txt
    # curl -X GET "http://localhost:8080/status/200" -H "accept:text/plain"
  artifacts:
    when: always
    paths:
      - build/

api testing:
  stage: api test
  image:
    name: vdespa/newman  #newman cli for postman
    entrypoint: [""]
  script:
    - newman --version
    - newman run "httpbin.org.postman_collection.json" --environment httpbin.org.postman_environment.json --reporters cli,htmlextra,junit --reporter-htmlextra-export "newman/report.html" --reporter-junit-export "newman/report.xml"
  artifacts:
    when: always
    paths:
      - newman/
    reports:
      junit: newman/report.xml


